Delay average statistic
signal18/replication-manager pull request #521
Opened 2023-11-28 05:52 UTC by ahfa92

Adding delay average statistics for failover weighting. Already got the statistic, but still waiting for the weighting calculation. Kindly suggest the weighting algorithm.
values:
delay: average delay
delayCount: counter of lag more than 0 seconds occured
slaveErrCount: counter of slave error
counter: total counter

if we want to see percentage of delay count we can do delayCount / counter and so does with slave err percentage slaveErrCount
based on the logic we should pick the lowest value available.

2023-12-05 17:13 UTC, svaroqui requested changes

2023-12-05 17:13 UTC, svaroqui commented on cluster/srv.go
Could we organize code to put most functions in cluster_stat.go file !

2023-12-06 08:43 UTC, ahfa92 commented on cluster/srv.go
Sure

2023-12-06 08:44 UTC, ahfa92 commented
Hi @svaroqui, I already updated the code. Kindly check.

2023-12-06 08:55 UTC, merged